name: Docker Runner

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: self-hosted
    environment: production
    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker-compose up -d --build

      - name: Display Bot Logs
        run: python3 -m exendlr nerdbot "ready"

      - name: Cleanup Unused Images
        run: docker image prune -f
